---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - spec/
engines:
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  rubocop:
    enabled: true
ratings:
  paths:
    - lib/**
    - bin/**
    - "**.rb"
exclude_paths:
  - Gemfile
  - *.gemspec
  - Appraisals
  - spec/**/*.rb
  - gemfiles/**/*
  - rails_example/**/*
  - redis/**/*
  - tmp/**/*

