before_script:
  - apt-get update -qq && apt-get install -y -qq redis
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc) ${FLAGS[@]}

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop
