language: ruby
services:
  - redis-server
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - 2.0.0
  - 2.1.2
  - 2.2.2
gemfile:
  - gemfiles/sidekiq_2.15.gemfile
  - gemfiles/sidekiq_2.16.gemfile
  - gemfiles/sidekiq_2.17.gemfile
  - gemfiles/sidekiq_3.0.gemfile
  - gemfiles/sidekiq_develop.gemfile
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - mikael@zoolutions.se
matrix:
  allow_failures:
    - rvm: rbx-19mode
