sudo: false
language: ruby
cache: bundler
services:
  - redis-server
before_script:
  - bundle exec rubocop
script:
  - bundle exec rspec spec
rvm:
  - jruby-19mode
  - jruby-9.0.0.0
  - rbx-2
  - 2.0.0
  - 2.1.7
  - 2.2.3
gemfile:
  - gemfiles/sidekiq_develop.gemfile
  - gemfiles/sidekiq_2.17.gemfile
  - gemfiles/sidekiq_3.0.gemfile
  - gemfiles/sidekiq_3.1.gemfile
  - gemfiles/sidekiq_3.2.gemfile
  - gemfiles/sidekiq_3.3.gemfile
# branches:
#   only:
#     - master
notifications:
  email:
    recipients:
      - mikael@zoolutions.se
matrix:
  fast_finish: true
